version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
volumes:
  mongo-data:  # MongoDB data volume
